### ISSUE TITLE
Theme was working fine, but cursor went missing suddenly

### ISSUE THREAD

**Issue by konti-dylan** [wesbos/cobalt2-vscode#82]
Hi,

i have been using this with the recommended settings. However, the cursor went missing in recent vscode update and i couldn't get it back.

In addition, every vscode updates requires me to "reactivate" Custom CSS and JS..is this the case for everyone?

![image](https://user-images.githubusercontent.com/36297095/36023536-c0e767a4-0dc7-11e8-901b-a8964a02cd59.png)

**Comment by abdelrahmanrifai** [comment]
The new VSCode update introduced a new setting for cursor width `editor.cursorWidth` that you can use.

To fix your issue:
- Change `editor.cursorStyle` from `underline-thin` to `line`
- Add `"editor.cursorWidth": 3`
- Open `.vscodestyles.css` file and **remove the Fat Cursor block**
```CSS
/*
  Fat Cursor.
  This overwrites the "underline thin" style since that is one that can be styled with CSS
  So set your settings to:
  "editor.cursorStyle": "underline-thin",
*/
.monaco-editor .cursors-layer.cursor-underline-thin-style > .cursor {
  border-bottom-width: 0;
  border-left-width: 3px;
  border-left-style: solid;
  background: transparent !important;
  box-sizing: border-box;
}
```
- Finally `Reload Custom CSS and JS`

I already opened a pull request #81 to fix that.

_**Reloading custom CSS and JS after every VSCode update is a must!**_
